### ISSUE TITLE
 Cannot connect to host

### ISSUE THREAD

**Issue by viziashkin** [MrBearPresident/JBL_Soundbar#2]
Hi. 

Very appreciate your custom integration and was happy to control the soundbar from the HASS. 
Had it working for a week or so, but now EQ, power and other things except volume do not work.

Do you mind helping me to identify the issue? What tools have you used to debug requests?

Obviously it cannot connect to the soundbar, but I'm wondering what could change if it has been working. JBL One app works fine. Tried to reset the soundbar to factory settings, reconnect to network, restart HA, reinitialize the integration - no luck. And again, volume is working, so IP is correct.

Model: JBL Bar 1000
Software: OneOS 2.3 (24.33.31.80.00)

Getting in logs:
jbl_integration/coordinator.py:104
`Error getting device info:`

jbl_integration/coordinator.py:212
`Error fetching data:
Error fetching data: Cannot connect to host 192.168.1.123:59152 ssl:default [Connect call failed ('192.168.1.123', 59152)]`

jbl_integration/coordinator.py:261
`Error getting EQ:
Error getting EQ: Cannot connect to host 192.168.1.123:80 ssl:default [Connect call failed ('192.168.1.123', 80)]`

**Comment by viziashkin** [comment]
That sucks. I thought updates are not automatic and I'd see some prompt, so also thought they already abandoned updating firmware. I guess if you manage to fix the problem it would be reasonable to check endpoints used for checking for updates and block them on router as I've done for my rooted WebOS TV.

**Comment by viziashkin** [comment]
Otherwise, I would buy some IR blaster to mimic remote signals. Opening the app each time I want to tune Low EQ at night is a pain in the ass.

**Comment by MrBearPresident** [comment]
I've found already something. 
So I used HTTP-Toolkit again (like I described [here](https://community.home-assistant.io/t/control-jbl-5-1-soundbar/219319/5?u=mrbearpresident)). I could see that all the commands that I use and not working anymore just switched to https. 
I am unable to get the certificate so the jbl bar accepts the https request.

But we are already making progress.

**Comment by MrBearPresident** [comment]
I have great news... after a long week reading trying, failing, and lots of frustration I cracked their client side key. 
Update comming up soon. 
Should all work again.

**Comment by viziashkin** [comment]
Great stuff!

**Comment by MrBearPresident** [comment]
Solved in 
[https://github.com/MrBearPresident/JBL_Soundbar/releases/tag/V1.1.2](https://github.com/MrBearPresident/JBL_Soundbar/releases/tag/V1.1.2)

**Comment by MrBearPresident** [comment]
Solved in 
[https://github.com/MrBearPresident/JBL_Soundbar/releases/tag/V1.1.2](https://github.com/MrBearPresident/JBL_Soundbar/releases/tag/V1.1.2)
