### ISSUE TITLE
Minor shortcomings

### ISSUE THREAD

**Issue by czesiu20** [MrBearPresident/JBL_Soundbar#3]
Hello, 
first of all thank you for your time and great integration.
You can add JBL 300 to the list of working devices.
The integration is working well. I've noticed only small things to fix.
1. I installed 1.1.2 but 1.1.1 is displayed. The name JBL 800 seems to be hardcoded. My device is JBL300
![obraz](https://github.com/user-attachments/assets/64a992ef-b7c2-4cf0-909b-d76e876bb204)

2. When configuring integration the "expected int" error is displayed. The default '5' seems to be set as text, not a value.
![obraz](https://github.com/user-attachments/assets/170beafd-3b69-4d9e-bac7-a1d789f15a7b)

3. When cleared and entered any digit the configuration succeeds. Even for non-existing device (for wrong IP)
![obraz](https://github.com/user-attachments/assets/767c7a68-d5a9-47e0-8421-eace2548a17f)

**Comment by MrBearPresident** [comment]
Good points that I already noted myself but didn't take the time to fix. 
It will be fixed in the 1.1.3 version. 
The last one however I didn't think of it yet. But I'll try to find a way for this. 

What firmware is your JBL Bar 300 running?

**Comment by czesiu20** [comment]
The latest 24.27.31.80.00
I've owned it for a few days. This integration is very helpful for me in my cinema I'm creating. I was looking for a way to switch between HDMI and Bluetooth (TV and projector). I would like to send you coffee, but I don't see such an option.

**Comment by MrBearPresident** [comment]
No need to buy me anything for now I just treat this as a hobby. 

I created a new branch [https://github.com/MrBearPresident/JBL_Soundbar/tree/prep-v1.1.3](https://github.com/MrBearPresident/JBL_Soundbar/tree/prep-v1.1.3)

If you are able you can test it.
Could you also check if the info (the working models) in the readme is correct.

**Comment by MrBearPresident** [comment]
I've made a pre-release version for you so if you use HACS this should be possible through that. 
![image](https://github.com/user-attachments/assets/d57ff937-d277-43fd-8767-3f930f2fb418)

**Comment by czesiu20** [comment]
Thank you.
I installed the new version and everything is fine. This issue can be closed.
The section Working models is OK for my device. 
I think both 24.27.31.80.00 and 24.33.31.80.00 columns can be merged as 24.X.31.80.00. Where X is probably kind/model number. More samples are needed to confirm this assumption.
