### ISSUE TITLE
Entity naming

### ISSUE THREAD

**Issue by viziashkin** [MrBearPresident/JBL_Soundbar#7]
Problem:
Currently, the integration creates entities named like "button.power", "button.mute". Those are too abstract. 

Proposed solution:
I think it would be more appropriate to prepend each entity with the device name to have a structure and avoid any conflicts with other integrations and existing entities.  Also, valid in case there are more than one soundbars

Example: 
device name: "JBL Bar 1000"
"button.mute" => "button.jbl_bar_1000_mute"

I think that's a standard since I see it in all the integrations I have. 

Example from home kit TV integration: 
![Screenshot_2024-11-11-16-47-24-58_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/ae240ae5-77a9-4d11-a071-43f6ac80e6f6)

**Comment by MrBearPresident** [comment]
Good point.
I've made work of it.

**Comment by MrBearPresident** [comment]
I've made a pre-release. If you're willing to test. 
To get the new entity ID's you'll have to delete and re-add the configuration. 

The entities now get linked to the device name. 
so for me it is : "number.jbl_bar_800_eq_1_low"
If your soundbar's name is "Soundbar Bedroom" it should result in "number.soundbar_bedroom_eq_1_low" . 
The device name is set in the jbl_app.


In HACS go to the integration and click "redownload"
Then choose the V1.2.1_beta
![image](https://github.com/user-attachments/assets/b3be06f1-114e-4881-8d82-f3a1828ba4dc)

**Comment by viziashkin** [comment]
Not a part of this issue, but have you looked into adding a control for rear speakers volume? I think that is the very last part missing from the integration

**Comment by MrBearPresident** [comment]
@viziashkin 
I've not implemented this, because I saw no immediate use for this + it was an extra command. 
With a baby in the house I've chosen to not give this priority over my daughter. 

But you can be my guest to try it yourself and add a push request. 

I've searched my notes and can set you on your way.

```
url = "https://192.148.4.66/httpapi.asp"
params = { 'command': "getRearSpeakerVolume"}
headers = {  'Accept-Encoding': "gzip"}
```

```
url = "https://192.148.4.66/httpapi.asp"
payload = "command=setRearSpeakerVolume&payload={\"volume\": \"3\"}"
headers = {  'Accept-Encoding': "gzip"}
```
